import { createSlice } from "@reduxjs/toolkit"

//createrslice is used to initilaoze a reducer function with some initial value


export const questionReducer=createSlice({
    name : 'questions',
    initialState : {
        queue : [],  //this will store the questions
        answers : [], // this will store the options
        trace : 0  //when we switch to another question trace will increase by 1
    },
    reducers : {
        //We can change the value of store only using actions
        //using createSlice we dont't need to crate action manually,resucer function will create it automatically 
        startExamAction : (state,action)=>{
            let {question,answers}=action.payload
            return {
                ...state,
                queue :  question, //by payload property we get the user input value
                answers : answers
            }
        },
        moveNextAction : (state)=>{
            return {
                ...state,
                trace : state.trace+1
            }
        },
        movePrevAction : (state)=>{
            return {
                ...state,
                trace : state.trace-1
            }
        },
        resetAllAction : ()=>{ //Action to reset all the values when we click on restart button in result component
            return {
                queue : [],  
                answers : [], 
                trace : 0
            }
        }
    }
})

export const {startExamAction, moveNextAction, movePrevAction,resetAllAction}=questionReducer.actions;
//questionReducer.actions is an object that contains all the action creators automatically generated by the createSlice function when you define your Redux slice

export default questionReducer.reducer;



